//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoP2PrecoCombustivel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_valor_combustivelEntities3 : DbContext
    {
        public db_valor_combustivelEntities3()
            : base("name=db_valor_combustivelEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ESTADO_COMBUSTIVEL> TB_ESTADO_COMBUSTIVEL { get; set; }
    }
}
